[package]
name = "html2json"
version = "0.1.0"
authors = ["bb010g <me@bb010g.com>"]
edition = "2018"

[dependencies]
html5ever = "0.22.5"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0.39"
